all:
  children:
    workstations:
      hosts:
        entreri:
          ansible_host: 10.0.0.193
    servers:
      hosts:
        baator:
          ansible_host: 10.0.0.162
    control:
      hosts:
        kimmuriel:
          ansible_host: 127.0.0.1
          ansible_connection: local
  vars:
    ansible_user: lantzops
